

Table accounts {
  id integer [primary key, unique, increment, not null]
  username string
  password string
}
Table journal_entry_groups {
  id integer [primary key]
  narration string
  description string
  is_cashflow_only boolean
}

Table allocations {
  id integer [primary key, not null, increment]
  journal_group_id integer [ref: > journal_entry_groups.id, note: 'Link to the journal entry group']
  start_date string
  end_date varchar(50)

  created_dt timestamp [default: `now()`]
  modified_dt timestamp [default: `now()`]

  indexes {
    (start_date, end_date) [unique]
    start_date
    end_date [name: 'end_date_index', unique]

  }

  Note: 'this table is used to determine the basis of dividends'
}

Table workflows{
  id integer [primary key, unique, increment,not null]
  event_id integer [ref:>events.id, unique]
  requestor_account_id integer [ref:>accounts.id]
  staff_id integer [ref:>accounts.id]
}
Table events {
  id integer [primary key]
  name string
  state string
  description string
}