
Table accounts {
  id integer [primary key, unique, increment, not null]
  username string
  password string
}
Table account_roles {
  id integer [primary key]
  account_id integer [ref: > accounts.id]
  role_id integer [ref: - roles.id]
}

Table account_business_units {
  id integer [primary key]
  business_unit_id integer [ref: > business_units.id]
  account_id integer [ref: - accounts.id]
}
Table accounts_kyc {
  id integer [primary key]
  account_id integer [ref: > accounts.id]
  kyc_id integer [ref: - kycs.id]
}

/*Roles access*/
Table roles {
  id integer [primary key]
  description string
  ref_name string
  created_by integer
  modified_by integer
  created_dt timestamp
  modified_dt timestamp
  is_accountive integer
}
Table permissions {
  id integer [primary key]
  description string
  ref_name string
  scope string
  sequence integer
  created_by integer
  modified_by integer
  created_dt timestamp
  modified_dt timestamp
  is_accountive integer
}
Table role_permissions {
  id integer [primary key]
  permission_id integer  [ref: > permissions.id]
  role_id integer [ref: > roles.id]
  created_by integer
  modified_by integer
  created_dt timestamp
  modified_dt timestamp
  is_accountive integer
}

/*KYC Collections*/
Table kycs {
  id integer [primary key]
  first_name string
  middle_name string
  last_name string
  birthdate date
  mobile_no string
  tel_no string
  email string
  spouse_name string

  
  civil_status_id string
  gender_id string
  education_id string
  source_income_id string
}


Table kyc_occupations {
  id integer [primary key]
  name string
  employer string
  kyc_id integer [ref: > kycs.id]
}
Table kyc_businesses {
  id integer [primary key]
  name string
  kyc_id integer [ref: > kycs.id]
  type string
  income string
}
Table kyc_addresses {
  id integer [primary key]
  kyc_id integer [ref: > kycs.id]
  type string [note: 'current, permanent, business']
  address string
  country string
  province string
  city string
  barangay string
}
Table kyc_medias{
  id integer [primary key]
  file_id integer [ref: - files.id]
  kyc_id integer [ref: > kycs.id]
}

/*Transactions*/
Table loan_trxs {
  id integer [primary key]
  loan_id integer [ref: - loans.id]
  amount integer
  account_id integer [ref: - accounts.id]
}
Table loan_trx_insurance {
  id integer [primary key]
  loan_trx_id integer [ref : - loan_trxs.id]
  insurance_id integer [ref : - insurances.id]
}
Table collections {
  id integer [primary key]
  reference_id string
}
Table collection_trxs {
  id integer [primary key]
  collection_id integer [ref: > collections.id]
  integration_id integer [ref: > integrations.id]
  amount string
  account_id integer [ref: - accounts.id]
}
Table expense_trxs {
  id integer [primary key]
  name string
  amount integer
}
Table fee_trxs{
  id integer [primary key]
  name string
  default_amount integer
  amount integer
}
Table sales {
  id integer [primary key]
  reference_id string
}
Table sale_trxs {
  id integer [primary key]
  sale_id integer [ref: > sales.id]
  inventory_movement_id integer [ref: > inventory_movements.id]
  amount integer
  account_id integer [ref: > accounts.id]
}
Table purchases {
  id integer [primary key]
  reference_id string
  supplier_id integer [ref: > suppliers.id]
}
Table purchase_trxs{
  id integer [primary key]
  inventory_movement_id integer [ref: > inventory_movements.id]
  amount string
  uom string
  unit_price string
  trx_date string
  purchase_id integer [ref: > purchases.id]
}
Table inventory_writeoff_trxs{
  id integer [primary key]
  inventory_movement_id integer [ref: > inventory_movements.id]
}
Table purchase_return_trxs {
  id integer [primary key]
  inventory_movement_id integer [ref: > inventory_movements.id]
  purchase_id integer [ref: > purchases.id]
}




/* Center transactions */
Table centers_trxs {
  id integer [primary key]
  integration_id integer [ref:> integrations.id]
}



/*Accounting transactions*/

Table journal_entry_groups {
  id integer [primary key]
  narration string
  description string
  is_cashflow_only boolean
}

Table journal_entries {
  id integer [primary key]
  journal_entries_group_id integer [ref:> journal_entry_groups.id]
  chart_account_id integer [ref: > chart_accounts.id]
  
  debit_amount integer
  credit_amount integer
  
  qty integer
}
Table journal_entry_files{
  id integer [primary key]
  file_id integer [ref: > files.id]
  journal_entry_group_id integer [ref: > journal_entry_groups.id]
}

/*Savings transactions*/
Table withdraw_trxs {
  id integer [primary key]
  ref_no string
  account_id integer [ref: > accounts.id]
  staff_center_id integer [ref: - staff_centers.id]
  name string
  amount string
  relation string
}


/* Integrations */
Table integrations {
  id integer [primary key]
  source_type string [note: 'pertains to collections']
  source_id integer [note: 'any trx that requires entry like purchase trxs']
}


/*Workflow*/
Table workflows{
  id integer [primary key, unique, increment,not null]
  event_id integer [ref:>events.id, unique]
  requestor_account_id integer [ref:>accounts.id]
  staff_id integer [ref:>accounts.id]
}
Table events {
  id integer [primary key]
  name string
  state string
  description string
}


/*Client control*/
Table staff_centers{
  id integer [primary key]
  account_id integer [ref: > accounts.id]
  center_id  integer [ref: > centers.id]
}
Table account_centers {
  id integer [primary key]
  account_id integer [ref: > accounts.id]
  center_id integer [ref: > centers.id]
}

/**Inventory*/

Table inventories{
  id integer [primary key]
  selling_price string
  qty integer
  min_qty integer
  max_qty integer
}

Table inventory_movements{
  id integer [primary key]
  inventory_id integer [ref: > inventories.id]
  qty integer
  type string [note: 'in or out'] 
}


/*Enums*/
Table business_units {
  id integer [primary key]
  name string
  ref_name string
}
Table centers {
  id integer [primary key]
  address string
  country string
  province string
  city string
  barangay string
}
Table suppliers{
  id integer [primary key]
  name string
  address string
}

Table loans{
  id integer [primary key]
  term string
  interest_rate integer
  insurance_id integer [ref : > insurances.id]
  name string
  description string
  business_unit_id integer [ref : > business_units.id]
}


Table insurances {
  id integer [primary key]
  name string
  description string
}


/*
Penalties
Fees
Expenses
Chart of Accounts
*/
Table enums {
  id integer [primary key]
  type string
  key string
  value string
  value_type string [note: 'fixed or percentage or text']
  description string
  allow_edit boolean
  allow_delete boolean
  allow_add boolean
}

/*Chart of Accounts*/
Table chart_accounts {
  id integer [primary key]
  name string
  category string [note: 'asset,liability,equity,expense,income']
}

Table files {
  id integer [primary key]
  type string [note:'png, jpeg, pdf']
}

/*
basis of dividends
*/
Table allocations {
  id integer [primary key, not null, increment]
  journal_entry_group_id integer [ref: > journal_entry_groups.id]
  start_date string
  end_date varchar(50)

  indexes {
    (start_date, end_date) [unique]
    start_date
    end_date [name: 'end_date_index', note: 'Date']
    booking_date [type: hash]
  }

  Note {
    'this table is used to determine the basis of dividends'
  }
}
